config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  resources :posts, only: [:create, :destroy]
  
  resources :lists do
    collection do
      match 'search', via: [:get, :post]
      post 'toggle_action'
    end  
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :posts, dependent: :destroy
  default_scope -> { order(updated_at: :desc) }
  validates :name, presence: true, length: { maximum: 30 }, uniqueness: true

  # 期限が一番早い未完了のTODOの日付を取り出す
  # @return [Date] 期限が一番早い未完了のTODOの日付
  def first_Incomplete_expiration_date
    posts.unscope(:order).order(:expiration_date).find_by(complete_flg: 0).expiration_date
  end

  # 検索ワードを元にリスト名からリストを検索する
  # @param [String] search 検索ワード
  # @return [List] 検索ワードに一致したリストを返す
  # @return [List] 検索ワードに一致しない場合は全てのリストを返す
  def self.search(search)
    if search
      List.where(['name LIKE ?', "%#{search}%"])
    else
      List.all
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :list
  default_scope -> { order(created_at: :desc) }
  validates :content, presence: true, uniqueness: { scope: [:list_id] }, length: { maximum: 30 }
  validates :expiration_date, presence: true

  # 検索ワードを元にTODO名からTODOを検索する
  # @param [String] search 検索ワード
  # @return [List] 検索ワードに一致したTODOを返す
  # @return [List] 検索ワードに一致しない場合は全てのTODOを返す
  def self.search(search)
    if search
      Post.where(['content LIKE ?', "%#{search}%"])
    else
      Post.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ListsHelper

  # リスト有効期限の更新
  def list_expiration_date
    date = @list.first_Incomplete_expiration_date
    @list.update_attributes(expiration_date: date)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  # リスト一覧表示時に一覧を生成するアクション
  def new
    @list = List.new
    @lists = List.paginate(page: params[:page])
  end

  # ポスト一覧表示時に一覧を生成するアクション
  def show
    @list = List.find(params[:id])
    @post = @list.posts.build
    @posts = @list.posts.paginate(page: params[:page])
  end
  
  # リスト作成時のアクション
  def create
    @list = List.new(list_params)
    @lists = List.paginate(page: params[:page])
    if @list.save
      flash[:success] = '新しいリストが作成されました。'
      redirect_to new_list_path
    else
      render :new
    end
  end
  
  # リスト削除時のアクション
  def destroy
    @list = List.find(params[:id])
    @list.destroy
    render :json => {:list => @list}
  end

  # 検索一覧を生成するアクション
  def search
    @lists = List.search(params[:search])
    @posts = Post.search(params[:search])
    @search_total = @lists.count + @posts.count
  end

  # TODOの完了フラグを切り替えるアクション
  def toggle_action
    @post = Post.find(params[:id])
    @list = List.find(@post.list_id)
    @post.complete_flg = @post.complete_flg == 0
    @post.save
    # リストの有効期限を更新
    list_expiration_date
  end

  private

  # リストのパラメータ
  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # TODO作成時のアクション
  def create
    @list = List.find(post_params[:list_id])
    @post = @list.posts.build(post_params)
    @posts = @list.posts.paginate(page: params[:page])
    if @post.save
      # リスト有効期限を更新
      list_expiration_date
      flash[:success] = '新しいTODOが作成されました。'
      redirect_to "/lists/#{ post_params[:list_id] }"
    else
      render 'lists/show'
    end
  end
  
  # TODO削除時のアクション
  def destroy
    @post = Post.find(params[:id])
    @list = List.find(@post.list_id)
    @post.destroy
    list_expiration_date
    render :json => {:post => @post}
  end

  private
  
  # リストのパラメータ
  def post_params
    params.require(:post).permit(:list_id, :content, :expiration_date)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # ページごとの完全なタイトルを返す
  # @param [String] page_title 各ページのタイトル
  # @return [String] ページタイトルと「ToDoApp」を連結した文字列
  # @return [String] ページタイトルが存在しない場合は「ToDoApp」の文字列のみ
  def full_title(page_title = '')
    base_title = 'ToDoApp'
    if page_title.blank?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
    
  # 日本式の日付に変換
  # @param [TimeWithZone] date 日付
  # @return [String] 日付を変換した文字列
  # @return [nil] TimeWithZone型以外の場合
  def convert_jp_date(date)
    date.strftime('%Y年 %m月 %d日') if date.kind_of?(ActiveSupport::TimeWithZone)
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'partials/rails_default' %>
  </head>

  <body>
    <%= render 'partials/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_list_search.html.erb
<% @lists_name = 'リスト' %>

<%= render partial: 'search_message', locals: { item: @lists, name: @lists_name } %>

<ul class='lists search-margin'>
  <% @lists.each do |list| %>
    <li>
      <div class='contet'><%= link_to list.name, "lists/#{list.id}" %></div>
      <div class='timestamp right'>作成日 ： <%= convert_jp_date(list.created_at) %></div>
    </li>
  <% end %>
</ul>

app/views/lists/_lists.html.erb
<ul class='lists lists-margin'>
  <% @lists.each do |list| %>
    <li id="list-<%= list.id %>">
      <table>
        <tr>
          <th>
            <%= link_to list.name, list %>
            <p><%= list.posts.count %> 個中 <%= list.posts.where(complete_flg: 1).count %> 個がチェック済み</p>
            <p>作成日　： <%#= list.created_at.strftime("%Y年 %m月 %d日") %><%= convert_jp_date(list.created_at) %></p>
            <% if list.expiration_date.present? %>
              <p>有効期限： <%= list.expiration_date.strftime("%Y年 %m月 %d日") %></p>
            <% end %>
          </th>
          <th class='garbage'>
            <%= link_to image_tag('garbage.png'), list_path(list.id), method: :delete, data: { confirm: '本当に削除してもよろしいですか' }, class: 'list_delete', remote: true %>
          </th>
        </tr>
      </table>
    </li>
  <% end %>
</ul>

app/views/lists/_post_search.html.erb
<% @posts_name = 'TODO' %>

<%= render partial: 'search_message', locals: { item: @posts, name: @posts_name } %>

<ul class='lists search-margin'>
  <% @posts.each do |post| %>
  <li id="post-<%= post.id %>">
      <table>
        <tr>
          <th>
            <div class='content'><%= link_to post.content, "lists/#{post.list.id}" %></div>
            <p>リスト： <%= post.list.name %></p>
          </th>
          <th>
            <div class='timestamp right'>作成日 ： <%= convert_jp_date(post.created_at) %></div>
            <div class='timestamp right'>期　限 ： <%= convert_jp_date(post.expiration_date) %></div>
          </th>
        </tr>
      </table>
    </li>
  <% end %>
</ul>

app/views/lists/_search_message.html.erb
<% if item.count != List.all.count && item.count > 0 %>
  <div class='alert alert-success'><%= name %>が <%= item.count %> 件見つかりました。</div>
<% elsif item.count == 0 %>
  <div class='alert alert-danger'><%= name %>が見つかりませんでした。</div>
<% end %>

app/views/lists/new.html.erb
<% provide(:title, 'Lists') %>

<p>新しいTODOを作成する</p>
<%= form_for @list do |f| %>

  <%= f.text_field :name, class: 'form_input' %>

  <%= f.submit 'リストの作成', class: 'btn btn-primary' %>

  <%= render 'shared/error_messages', object: f.object %>
<% end %>

<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

<%= will_paginate @lists %>

<%= render 'lists' %>

<%= will_paginate @lists %>

app/views/lists/search.html.erb
<!-- 検索ページ -->

<!-- 検索フォーム -->
<%= form_for new_list_path, url: search_lists_path do |f| %>
  <p>
    <%= text_field_tag :search, params[:search], class: 'form_input'%>
    <%= submit_tag '検索', name: nil, class: 'btn btn-primary' %>
  </p>
<% end %>
<!-- 検索フォーム -->

<!-- 検索結果 -->
<% if @search_total != Post.all.count + List.all.count %>
  <%= render 'post_search' %>

  <%= render 'list_search' %>
<% end %>
<!-- 検索結果 -->

app/views/lists/show.html.erb
<%= provide(:title, @list.name) %>
<div class='title'>
  <h1><%= @list.name %></h1>
</div>

<!-- TODO作成フォーム -->
<p>新しいTODOを作成する</p>
<%= form_for @post do |f| %>
  <%= f.hidden_field :list_id, { 'list_id' => @list.id } %>

  <%= f.text_field :content, class: 'form_input', :placeholder => 'TODOを入力して下さい' %><br>
  <p>期　限</p>
  <%= f.date_field :expiration_date, class: 'form_input' %>

  <%= f.submit 'TODOの追加', class: 'btn btn-primary' %>

  <%= render 'shared/error_messages', object: f.object %>
<% end %>
<!-- TODO作成フォーム -->

<!-- 成功時メッセージ -->
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>
<!-- 成功時メッセージ -->

<!-- TODOリスト -->
<% if @list.posts.any? %>
  <%= will_paginate @posts %>

  <ol class='posts'>
    <%= render @posts %>
  </ol>

  <%= will_paginate @posts %>
<% else %>
  <div class='alert alert-danger'>登録されたTODOはありません。</div>
<% end %>
<!-- TODOリスト -->

app/views/partials/_header.html.erb
<header class='navbar navbar-fixed-top navbar-inverse'>
  <div class='container'>
    <%= link_to 'TODOリスト', new_list_path, id: 'logo' %>
    <nav>
      <ul class='nav navbar-nav navbar-right'>
        <li><%= link_to '検索', search_lists_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/partials/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <table>
    <tr>
      <th>
        <!-- TODO一覧 -->
        <div class='content'><%= post.content %></div>
        <div class='timestamp'>
          作成日 ： <%= convert_jp_date(post.created_at) %>
        </div>
        <div class='timestamp'>
          期　限 ： <%= convert_jp_date(post.expiration_date) %>
        </div>
        <!-- TODO一覧 -->
      </th>
      <!-- 完了ボタン -->
      <th class='button'>
        <%= form_tag( { controller: 'lists', action: 'toggle_action' }, remote: true ) do %>
          <%= hidden_field_tag :id, post.id  %>
            <% if post.complete_flg == 0 %>
              <%= submit_tag('未完了', id: 'incomplete', class: 'btn btn-danger comp-btn') %>
            <% else %>
              <%= submit_tag('完了', id: 'complete', class: 'btn btn-success active comp-btn') %>
            <% end %>
        <% end %>
      </th>
      <th class="garbage">
        <%= link_to image_tag('garbage.png'), post_path(post.id), method: :delete, data: { confirm: '本当に削除してもよろしいですか' }, class: 'post_delete', remote: true %>
      </th>
      <!-- 完了ボタン -->
    </tr>
  </table>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id='error_explanation'>
    <div class='alert alert-danger'>
      <%= object.errors.count %> 件のエラーがあります。
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class='center jumbotron'>
  <h1>Welcome to the ToDoApp</h1>

  <h2>
    This is the home page for the
    <a href='http://www.team-lab.com/'>Team.lab</a>
    sample application.
  </h2>

  <%= link_to 'Start now!', new_list_path, class: 'btn btn-lg btn-primary' %>
</div>